#!/usr/bin/env bash
set -euo pipefail

THIS_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
source "$THIS_DIR/../common.sh"

launch_pepo_geometry3k() {
    pr_default MODEL_PATH "Qwen/Qwen2.5-VL-3B-Instruct"
    pr_default TRAIN_FILES "$DATA_ROOT/geometry3k/train.parquet"
    pr_default VAL_FILES "$DATA_ROOT/geometry3k/test.parquet"
    METHOD_COMMON_ARGS=(
        "data.train_files=$TRAIN_FILES"
        "data.val_files=$VAL_FILES"
        "data.prompt_key=problem"
        "data.answer_key=answer"
        "data.image_key=images"
        "data.video_key=videos"
        "data.format_prompt=$ROOT_DIR/examples/format_prompt/pepo.jinja"
        "data.filter_overlong_prompts=true"
        "data.min_pixels=3136"
        "data.max_pixels=12845056"
        "data.max_prompt_length=1024"
        "data.max_response_length=1024"
        "data.rollout_batch_size=8"
        "data.mini_rollout_batch_size=null"
        "data.val_batch_size=512"
        "algorithm.adv_estimator=grpo"
        "algorithm.disable_kl=false"
        "algorithm.use_kl_loss=true"
        "algorithm.kl_penalty=low_var_kl"
        "algorithm.kl_coef=0.001"
        "algorithm.log_entropy=true"
        "worker.actor.use_torch_compile=false"
        "worker.actor.model.enable_gradient_checkpointing=true"
        "worker.actor.model.trust_remote_code=true"
        "worker.actor.model.freeze_vision_tower=false"
        "worker.actor.optim.lr=1e-6"
        "worker.actor.optim.lr_scheduler_type=cosine"
        "worker.actor.optim.strategy=adamw_bf16"
        "worker.actor.global_batch_size=8"
        "worker.actor.micro_batch_size_per_device_for_update=2"
        "worker.actor.micro_batch_size_per_device_for_experience=8"
        "worker.actor.clip_ratio_low=0.2"
        "worker.actor.clip_ratio_high=0.2"
        "worker.actor.loss_avg_mode=seq"
        "worker.actor.fsdp.torch_dtype=bf16"
        "worker.ref.fsdp.torch_dtype=bf16"
        "worker.rollout.n=8"
        "worker.rollout.temperature=1.0"
        "worker.rollout.top_p=1.0"
        "worker.rollout.top_k=50"
        "worker.rollout.tensor_parallel_size=1"
        "worker.rollout.gpu_memory_utilization=0.6"
        "worker.rollout.enable_chunked_prefill=false"
        "worker.rollout.enforce_eager=true"
        "worker.rollout.val_override_config.n=8"
        "worker.rollout.val_override_config.temperature=1.0"
        "worker.rollout.val_override_config.top_p=1.0"
        "worker.reward.reward_function=$ROOT_DIR/examples/reward_function/r1v.py:compute_score"
        "worker.reward.reward_function_kwargs={\"format_weight\":0.5}"
        "trainer.project_name=PEPO-Reproduce"
        "trainer.n_gpus_per_node=8"
        "trainer.total_epochs=1"
        "trainer.val_freq=400"
        "trainer.save_freq=400"
        "trainer.val_generations_to_log=5"
        "trainer.val_before_train=true"
        "trainer.find_last_checkpoint=true"
        "trainer.save_limit=1"
    )
    launch_training "$@"
}
