#!/usr/bin/env bash
set -euo pipefail

THIS_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
source "$THIS_DIR/../common.sh"

# VGPO's train_vgpo_7B.sh and examples/configs/config.yaml of the official code (a DAPO recipe from VPPO-RL).
launch_vgpo() {
    pr_default MODEL_PATH "Qwen/Qwen2.5-VL-7B-Instruct"
    METHOD_COMMON_ARGS=(
        "data.train_files=$DATA_ROOT/virl39k/train.parquet"
        "data.val_files=$DATA_ROOT/mmk12/test.parquet"
        "data.prompt_key=problem"
        "data.answer_key=answer"
        "data.image_key=images"
        "data.video_key=videos"
        "data.format_prompt=$ROOT_DIR/examples/format_prompt/math_perception.jinja"
        "data.filter_overlong_prompts=true"
        "data.max_prompt_length=4096"
        "data.max_response_length=2048"
        "data.rollout_batch_size=512"
        "data.mini_rollout_batch_size=null"
        "data.val_batch_size=512"
        "data.min_pixels=262144"
        "data.max_pixels=4194304"
        "data.seed=1"
        "algorithm.adv_estimator=grpo"
        "algorithm.disable_kl=true"
        "algorithm.use_kl_loss=false"
        "algorithm.log_entropy=false"
        "algorithm.online_filtering=true"
        "algorithm.filter_key=accuracy"
        "algorithm.filter_low=0.01"
        "algorithm.filter_high=0.99"
        "worker.actor.model.enable_gradient_checkpointing=true"
        "worker.actor.model.trust_remote_code=true"
        "worker.actor.model.freeze_vision_tower=false"
        "worker.actor.optim.lr=1e-6"
        "worker.actor.optim.weight_decay=1e-2"
        "worker.actor.optim.strategy=adamw_bf16"
        "worker.actor.global_batch_size=128"
        "worker.actor.micro_batch_size_per_device_for_update=4"
        "worker.actor.micro_batch_size_per_device_for_experience=16"
        "worker.actor.dynamic_batching=true"
        "worker.actor.clip_ratio_low=0.2"
        "worker.actor.clip_ratio_high=0.28"
        "worker.actor.fsdp.torch_dtype=bf16"
        "worker.rollout.n=8"
        "worker.rollout.temperature=1.0"
        "worker.rollout.top_p=0.99"
        "worker.rollout.tensor_parallel_size=2"
        "worker.rollout.gpu_memory_utilization=0.9"
        "worker.rollout.max_num_batched_tokens=8192"
        "worker.rollout.enable_chunked_prefill=false"
        "worker.rollout.val_override_config.n=1"
        "worker.rollout.val_override_config.temperature=0.6"
        "worker.rollout.val_override_config.top_p=0.95"
        "worker.reward.reward_function=$ROOT_DIR/examples/reward_function/math.py:compute_score_wo_format"
        "trainer.project_name=VGPO-Reproduce"
        "trainer.n_gpus_per_node=8"
        "trainer.total_epochs=2"
        "trainer.val_freq=5"
        "trainer.save_freq=5"
        "trainer.save_limit=1"
        "trainer.val_generations_to_log=3"
        "trainer.val_before_train=true"
        "trainer.find_last_checkpoint=true"
        "trainer.max_try_make_batch=-1"
    )
    launch_training "$@"
}

# VGPO on top of the recipe: last-layer prototype scores before the update, factors per prompt group.
VGPO_ARGS=(
    "algorithm.visual_sensitivity_metric=hidden_state_similarity"
    "algorithm.visual_sensitivity_hidden_metric=cosine"
    "algorithm.visual_sensitivity_hidden_layers=last"
    "algorithm.visual_sensitivity_hidden_pooling=prototype"
    "algorithm.visual_sensitivity_reference=old"
    "algorithm.visual_token=auto"
    "algorithm.advantage_scaling_method=vgpo"
    "algorithm.vgpo_compensation_strength=0.3"
    "algorithm.vgpo_gate_tail_ratio=0.5"
    "algorithm.vgpo_gate_top_ratio=0.2"
)
