#!/usr/bin/env bash
set -euo pipefail

THIS_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
source "$THIS_DIR/../common.sh"

# VCSD (arXiv 2607.21556) setting: self-distillation from an EMA of the student (rate 0.05) on ViRL39K,
# 32 prompts x 8 rollouts and one update per step, 90 steps, lr 2e-6 after 10 warm-up steps, max response 1,024,
# the target sharpened by the contrast with a black image (alpha 1, beta 0.1, end-of-sequence tokens kept),
# forward KL at T_KD = 2 times T_KD^2, the official chat template (an empty think block) and tokenizer.
launch_vcsd() {
    METHOD_COMMON_ARGS=(
        "data.train_files=$DATA_ROOT/virl39k/train.parquet"
        "data.val_files=$DATA_ROOT/mmk12/test.parquet"
        "data.prompt_key=problem"
        "data.answer_key=answer"
        "data.image_key=images"
        "data.video_key=videos"
        "data.format_prompt=null"
        "data.override_chat_template=$ROOT_DIR/examples/chat_template/qwen_no_thinking.jinja"
        "data.filter_overlong_prompts=true"
        "data.min_pixels=262144"
        "data.max_pixels=4194304"
        "data.max_prompt_length=6144"
        "data.max_response_length=1024"
        "data.rollout_batch_size=32"
        "data.val_batch_size=512"
        "algorithm.disable_kl=true"
        "algorithm.use_kl_loss=false"
        "algorithm.log_entropy=true"
        "worker.teacher.source=ema"
        "worker.teacher.ema_rate=0.05"
        "algorithm.distill_loss_coef=1.0"
        "algorithm.policy_loss_coef=0.0"
        "algorithm.distill_target=contrast_sharpened"
        "algorithm.distill_contrast_view=black"
        "algorithm.distill_divergence=forward_kl"
        "algorithm.distill_temperature=2.0"
        "algorithm.distill_temperature_scope=all"
        "algorithm.vcsd_alpha=1.0"
        "algorithm.vcsd_support_beta=0.1"
        "algorithm.vcsd_anchor_coef=1.0"
        "algorithm.vcsd_keep_token_ids=auto"
        "worker.actor.loss_avg_mode=token"
        "worker.actor.model.plain_think_tokens=false"
        "worker.actor.model.enable_gradient_checkpointing=true"
        "worker.actor.model.trust_remote_code=true"
        "worker.actor.model.freeze_vision_tower=false"
        "worker.actor.optim.lr=2e-6"
        "worker.actor.optim.lr_warmup_steps=10"
        "worker.actor.optim.weight_decay=1e-2"
        "worker.actor.optim.strategy=adamw"
        "worker.actor.max_grad_norm=1.0"
        "worker.actor.global_batch_size=32"
        "worker.actor.micro_batch_size_per_device_for_update=4"
        "worker.actor.micro_batch_size_per_device_for_experience=8"
        "worker.rollout.n=8"
        "worker.rollout.temperature=1.0"
        "worker.rollout.top_p=1.0"
        "worker.rollout.tensor_parallel_size=1"
        "worker.rollout.gpu_memory_utilization=0.5"
        "worker.rollout.enable_chunked_prefill=false"
        "worker.rollout.enforce_eager=true"
        "worker.rollout.val_override_config.n=1"
        "worker.rollout.val_override_config.temperature=1.0"
        "worker.reward.reward_function=$ROOT_DIR/examples/reward_function/math.py:compute_score"
        "trainer.project_name=VCSD-Reproduce"
        "trainer.n_gpus_per_node=8"
        "trainer.max_steps=90"
        "trainer.val_freq=-1"
        "trainer.save_freq=10"
        "trainer.save_limit=1"
        "trainer.val_generations_to_log=5"
        "trainer.val_before_train=false"
        "trainer.find_last_checkpoint=true"
    )
    launch_training "$@"
}
