#!/usr/bin/env bash
set -euo pipefail

THIS_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
source "$THIS_DIR/../common.sh"

launch_full_vocab_sensitivity_geo3k() {
    pr_default MODEL_PATH "Qwen/Qwen2.5-VL-7B-Instruct"
    METHOD_COMMON_ARGS=(
        "data.train_files=$DATA_ROOT/vepo/train.parquet"
        "data.val_files=$DATA_ROOT/vepo/test.parquet"
        "data.prompt_key=problem"
        "data.answer_key=answer"
        "data.image_key=images"
        "data.video_key=videos"
        "data.format_prompt=null"
        "data.system_prompt=$ROOT_DIR/examples/system_prompt/vepo.txt"
        "data.filter_overlong_prompts=true"
        "data.min_pixels=262144"
        "data.max_pixels=1000000"
        "data.max_prompt_length=2048"
        "data.max_response_length=2048"
        "data.rollout_batch_size=512"
        "data.mini_rollout_batch_size=null"
        "data.val_batch_size=512"
        "algorithm.adv_estimator=grpo"
        "algorithm.use_kl_loss=false"
        "algorithm.disable_kl=true"
        "algorithm.invariant_entropy_coef=-0.001"
        "algorithm.entropy_loss_type=full"
        "algorithm.log_entropy=false"
        "worker.actor.model.enable_gradient_checkpointing=true"
        "worker.actor.model.trust_remote_code=true"
        "worker.actor.model.freeze_vision_tower=true"
        "worker.actor.optim.lr=1e-6"
        "worker.actor.optim.strategy=adamw_bf16"
        "worker.actor.global_batch_size=256"
        "worker.actor.clip_ratio_high=0.2"
        "worker.actor.micro_batch_size_per_device_for_update=4"
        "worker.actor.micro_batch_size_per_device_for_experience=4"
        "worker.actor.fsdp.torch_dtype=bf16"
        "worker.ref.fsdp.torch_dtype=bf16"
        "worker.rollout.n=12"
        "worker.rollout.temperature=1.0"
        "worker.rollout.top_p=1.0"
        "worker.rollout.tensor_parallel_size=4"
        "worker.rollout.gpu_memory_utilization=0.35"
        "worker.rollout.enable_chunked_prefill=false"
        "worker.rollout.enforce_eager=true"
        "worker.rollout.max_num_batched_tokens=4096"
        "worker.rollout.val_override_config.n=8"
        "worker.rollout.val_override_config.temperature=1.0"
        "worker.rollout.val_override_config.top_p=0.9"
        "worker.reward.reward_function=$ROOT_DIR/examples/reward_function/math.py:compute_score"
        "data.seed=42"
        "trainer.project_name=VEPO-Reproduce"
        "trainer.n_gpus_per_node=8"
        "trainer.total_epochs=20"
        "trainer.val_freq=20"
        "trainer.save_freq=20"
        "trainer.save_limit=1"
        "trainer.val_generations_to_log=5"
        "trainer.val_before_train=true"
        "trainer.find_last_checkpoint=true"
    )
    launch_training "$@"
}
