#!/usr/bin/env bash
set -euo pipefail

THIS_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
source "$THIS_DIR/../common.sh"

launch_vppo_matrix() {
    pr_default MODEL_PATH "Qwen/Qwen2.5-VL-7B-Instruct"
    METHOD_COMMON_ARGS=(
        "data.train_files=$DATA_ROOT/virl39k/train.parquet"
        "data.val_files=$DATA_ROOT/mmk12/test.parquet"
        "data.prompt_key=problem"
        "data.answer_key=answer"
        "data.image_key=images"
        "data.video_key=videos"
        "data.format_prompt=$ROOT_DIR/examples/format_prompt/math_perception.jinja"
        "data.filter_overlong_prompts=true"
        "data.max_prompt_length=4096"
        "data.max_response_length=2048"
        "data.rollout_batch_size=384"
        "data.mini_rollout_batch_size=null"
        "data.val_batch_size=512"
        "data.min_pixels=200704"
        "data.max_pixels=1003520"
        "algorithm.adv_estimator=grpo"
        "algorithm.use_kl_loss=true"
        "algorithm.kl_penalty=low_var_kl"
        "algorithm.kl_coef=0.01"
        "algorithm.log_entropy=false"
        "algorithm.disable_kl=true"
        "algorithm.online_filtering=true"
        "algorithm.filter_key=accuracy"
        "worker.actor.model.enable_gradient_checkpointing=true"
        "worker.actor.model.trust_remote_code=true"
        "worker.actor.model.freeze_vision_tower=false"
        "worker.actor.optim.lr=1e-6"
        "worker.actor.optim.strategy=adamw_bf16"
        "worker.actor.global_batch_size=128"
        "worker.actor.micro_batch_size_per_device_for_update=16"
        "worker.actor.micro_batch_size_per_device_for_experience=32"
        "worker.actor.clip_ratio_high=0.28"
        "worker.actor.dynamic_batching=false"
        "worker.actor.fsdp.torch_dtype=bf16"
        "worker.ref.dynamic_batching=false"
        "worker.ref.fsdp.torch_dtype=bf16"
        "worker.rollout.n=8"
        "worker.rollout.temperature=1.0"
        "worker.rollout.top_p=0.99"
        "worker.rollout.tensor_parallel_size=1"
        "worker.rollout.gpu_memory_utilization=0.9"
        "worker.rollout.enable_chunked_prefill=false"
        "worker.rollout.enforce_eager=true"
        "worker.rollout.val_override_config.n=8"
        "worker.rollout.val_override_config.temperature=1.0"
        "worker.rollout.val_override_config.top_p=0.99"
        "worker.reward.reward_function=$ROOT_DIR/examples/reward_function/math.py:compute_score_wo_format"
        "trainer.project_name=VPPO-Reproduce"
        "trainer.n_gpus_per_node=8"
        "trainer.total_epochs=2"
        "trainer.val_freq=5"
        "trainer.save_freq=5"
        "trainer.val_generations_to_log=3"
        "trainer.val_before_train=true"
        "trainer.find_last_checkpoint=true"
        "trainer.max_try_make_batch=-1"
        "trainer.save_limit=1"
    )
    launch_training "$@"
}
